import './globals.css'
import { Nanum_Gothic } from 'next/font/google'

const nanumGothic = Nanum_Gothic ({
  weight: ['400'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={nanumGothic.className} >  
        {children}
      </body>
    </html>
  )
}
